### PR TITLE
Remove debug println

### PR DESCRIPTION
**Pull request by amilsted**
It's filling up our test logs :p

### CODE REVIEW

**Comment by amilsted** [comment]
@Krastanov looks like the breakage on QuantumSymbolics is transient? At least not related to this change :)

**Comment by Krastanov** [comment]
indeed, the QuantumSymbolics failure is unrelated. LGTM

**Comment by amilsted** [comment]
Are you able to merge it? Looks like I don't have permission :)

**Comment by Krastanov** [comment]
I will merge and release.

@david-pl , could you check the permissions?

**Pull request merged**
