### PR TITLE
Define apply function that does not modify arguments

### PR DESCRIPTION
**Pull request by apkille**
In preparation for the Gaussian quantum information package. `apply` would be useful to define here, as other packages in QuantumSavory use `apply!`.

### CODE REVIEW

**Comment by apkille** [comment]
@krastanov pinging for review.

**Review by Krastanov — COMMENTED** [review]
I think this should just be `*`. That is the equivalent used in QuantumOptics and QuantumClifford.
Also, if it just happens that you have a structure that is not capable of in-place modifications, it is still fine to use a method with a `!` in the name (for the sake of having a small API). In general, the safe way to use an in-place modifying function would be to write something like

```
my_structure = my_function!(my_structure)
```

Sure, this is redundant for the cases where `my_structure` is mutable, but it is pretty useful when down the line you need to introduce a structure that is not mutable without introducing a new API.

Regrettably, this is just a convention -- there is no way to enforce it in this language yet.

Thus, my preference would be to close this PR

Apologies for the slow response.

**Comment by apkille** [comment]
@krastanov You make fair points. My only reasoning for introducing this into the API was for completeness. There's probably exceptions to this rule, but IMO if you have an in-place function you should usually have a corresponding out-of-place function. Since it's already implemented in QO and QuantumClifford, I agree with just using `*`.

**Comment by Krastanov** [comment]
yup, good point. As a precedent, `*` and `mul!` from `LinearAlgebra` follow the same separation

**Pull request closed without merging**
