### PR TITLE
Solve piracies and ambiguities

### PR DESCRIPTION
**Pull request by Tortar**
Part of https://github.com/QuantumSavory/QuantumSavory.jl/pull/143

### CODE REVIEW

**Comment by Tortar** [comment]
Also this one should be it

**Comment by Tortar** [comment]
Now tests should pass on all versions, the compat missed some entries and Aqua complained. So this could be merged I think

**Comment by Krastanov** [comment]
apologies for the delay on responding here, I am running a summer workshop next week (qnumerics.org) and prep has taken some of my time. FYI, in case I do not finish reviewing this family of PRs this week, I might be in a bit of radio silence next week during the workshop

**Comment by Tortar** [comment]
No problem, I'm not in a rush to finish all of this, but this one should be relatively easy to review and merging it would allow be to test in CI the main one, so if you have some time for review for this one this it will make everything a bit faster

**Comment by Krastanov** [comment]
the QuantumSavory failure is due to the upstreaming, so it is to be expected

**Pull request merged**
